server:
  port: 9901

spring:
  application:
    name: microservicecloud-consumer
  banner:
    charset: utf-8
  http:
   encoding:
     charset: UTF-8
     enabled: true
     force: true
  messages:
    encoding: UTF-8
  datasource:
       url: jdbc:mysql://127.0.0.1:3306/lin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
       username: root
       password: 123
       driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
    # 单机
#      defaultZone: http://localhost:8761/eureka/
    #集群
     defaultZone: http://eureka8761.com:8761/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
